# Diplomatura en Ciencia de Datos - UNNE - 2024
### Módulo 4: Aprendizaje Automático
### Clase 2: Modelos lineales para clasificación

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv('iris.csv')
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
#Nos quedamos solo con dos especies de Iris
filtered_df = df[df['variety'].isin(['Setosa', 'Virginica'])]
filtered_df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[100 rows x 5 columns]

In [6]:
df['variety'].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [7]:
filtered_df['variety'].value_counts()

variety
Setosa       50
Virginica    50
Name: count, dtype: int64

In [20]:
clase0 = df[df['variety'].isin(['Setosa'])].copy()
clase0.drop(columns='variety', inplace=True)

clase1 = df[df['variety'].isin(['Virginica'])].copy()
clase1.drop(columns='variety', inplace=True)

In [21]:
print(clase1)

     sepal.length  sepal.width  petal.length  petal.width
100           6.3          3.3           6.0          2.5
101           5.8          2.7           5.1          1.9
102           7.1          3.0           5.9          2.1
103           6.3          2.9           5.6          1.8
104           6.5          3.0           5.8          2.2
105           7.6          3.0           6.6          2.1
106           4.9          2.5           4.5          1.7
107           7.3          2.9           6.3          1.8
108           6.7          2.5           5.8          1.8
109           7.2          3.6           6.1          2.5
110           6.5          3.2           5.1          2.0
111           6.4          2.7           5.3          1.9
112           6.8          3.0           5.5          2.1
113           5.7          2.5           5.0          2.0
114           5.8          2.8           5.1          2.4
115           6.4          3.2           5.3          2.3
116           6.5          3.0           5.5          1.8
117           7.7          3.8           6.7          2.2
118           7.7          2.6           6.9          2.3
119           6.0          2.2           5.0          1.5
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [22]:
clase0 = clase0.to_numpy()
clase1 = clase1.to_numpy()

In [23]:
clase0.shape

(50, 4)

In [24]:
def sigmoide(z):
    return 1/(1+np.exp(-z))

In [25]:
def entrenar(x_train, y_train):
    for i in range(len(pesos)):
        suma1 = 0
        for k in range(N):
            suma1 += (sigmoide(modelo(x_train[k]))-y_train[k])*pesos[i]
        suma1*= 1/N
        pesos[i] -= lr*suma1

    suma2 = 0
    for k in range(N):
        suma2 += (sigmoide(modelo(x_train[k]))-y_train[k])
    suma2*= 1/N
    b[0] -=lr*suma2

In [26]:
def optimizar(x_train, y_train):
    global lr, b
    z = np.dot(x_train,pesos)+b
    a = sigmoide(z)
    for i in range(len(pesos)):
        suma1 = 0
        for k in range(x_train.shape[0]):
            suma1 += (a[k]-y_train[k])*pesos[i]
        suma1*= 1/(x_train.shape[0])
        pesos[i] -= lr*suma1

    suma2 = 0
    for k in range(x_train.shape[0]):
        suma2 += (a[k]-y_train[k])
    suma2*= 1/(x_train.shape[0])
    b[0] -=lr*suma2

def loss(x, y):
    z = np.dot(x,pesos)+b
    a = sigmoide(z)
    suma = 0
    for i in range(x.shape[0]):
        suma += y[i]*np.log(a[i])+(1-y[i])*np.log(1-a[i])
    suma *= (-1/x.shape[0])
    return suma

def ejecutar_modelo(epochs):
    global pesos, b, perdida, validacion
    pesos = np.random.normal(loc=1, scale=0.1, size=x_train.shape[1])
    b = np.random.normal(loc=0, scale=0.1, size=1)
    perdida = []
    validacion = []

    for i in range(epochs):
        optimizar(x_train, y_train)
        perdida.append(loss(x_train, y_train))
        validacion.append(loss(x_val, y_val))
        
    plt.plot(perdida, color = 'red')
    plt.plot(validacion, color ='blue')
    plt.show()

In [27]:
def separar(tam_entren, clase0, clase1):
    M = clase0.shape[0]+clase1.shape[0]
    L = int(M*tam_entren)
    print(L)
    x_train = np.concatenate((clase0[:L//2], clase1[:L//2]))
    print('x train: ', len(x_train))
    x_val = np.concatenate((clase0[L//2:], clase1[L//2:]))
    print('x val: ', len(x_val))
    y_train = np.concatenate(((np.zeros(L//2)), np.ones(L//2)))
    print('y train: ', len(y_train))
    y_val = np.concatenate(((np.zeros(len(x_val)//2)), np.ones(len(x_val)//2)))
    print('y val: ', len(y_val))

    return x_train, y_train, x_val, y_val

In [ ]:
'''pesos = np.random.normal(loc=1, scale=0.1, size=x_train.shape[1])
b = np.random.normal(loc=0, scale=0.1, size=1)
lr = 0.1
#N = x_train.shape[0]
perdida = []
validacion = []

for i in range(100):
    optimizar(x_train, y_train)
    perdida.append(loss(x_train, y_train))
    validacion.append(loss(x_val, y_val))
    
plt.plot(perdida, color = 'red')
plt.plot(validacion, color ='blue')
plt.show()'''

In [ ]:
#IRIS
dataset = separar(0.3, clase0, clase1)
x_train = dataset[0]
y_train = dataset[1]
x_val = dataset[2]
y_val = dataset[3]

pesos = np.random.normal(loc=1, scale=0.2, size=x_train.shape[1])
b = np.random.normal(loc=1, scale=0.2, size=1)
lr = 0.1
#N = x_train.shape[0]
perdida = []
validacion = []

for i in range(100):
    optimizar(x_train, y_train)
    perdida.append(loss(x_train, y_train))
    validacion.append(loss(x_val, y_val))
    
plt.plot(perdida, color = 'red', label ='Error de entrenamiento')
plt.plot(validacion, color ='blue', label='Error de validación')

plt.title('Optimización del modelo')
plt.xlabel('Epochs')
plt.ylabel('Función de error')

plt.legend()
plt.show()

In [ ]:
#Numero de puntos a generar
num_points = 1000

#Generar puntos aleatorios de 2D
points_class_1a = np.random.randn(num_points // 2, 2) + np.array([2, 2])
points_class_2a = np.random.randn(num_points // 2, 2) + np.array([-2, -2])

#Combinar puntos
points = np.vstack((points_class_1a, points_class_2a))

#Poner etiquetas a los puntos (1 para clase 1, 0 para clase 2)
labels = np.hstack((np.ones(num_points // 2), np.zeros(num_points // 2)))

#Graficar
plt.figure(figsize=(8, 6))
plt.scatter(points_class_1a[:, 0], points_class_1a[:, 1], color='blue', label='Class 1')
plt.scatter(points_class_2a[:, 0], points_class_2a[:, 1], color='red', label='Class 2')

#Formato
plt.title('Puntos aproximadamente linealmente separables')
plt.xlabel('Eje X')
plt.ylabel('Eje Y')
plt.legend()

plt.show()

In [ ]:
#Numero de puntos a generar
num_points = 1000

#Definir el radio de separacion
inner_radius = 2.5
outer_radius = 3.5

#Distribuir la clase 1 uniformemente en el circulo interno
angles_class_1 = np.random.uniform(0, 2 * np.pi, num_points // 2)
radii_class_1 = np.sqrt(np.random.uniform(0, inner_radius**2, num_points // 2))
points_class_1 = np.vstack((radii_class_1 * np.cos(angles_class_1), radii_class_1 * np.sin(angles_class_1))).T

#Generar la clase 2 fuera del circulo externo
points_class_2 = np.random.randn(num_points // 2, 2)
distances_class_2 = np.sqrt(points_class_2[:, 0]**2 + points_class_2[:, 1]**2)
# Scale points so they fall outside the outer circle
points_class_2 = points_class_2 * (outer_radius / distances_class_2[:, np.newaxis] + 1)

# Graficar
plt.figure(figsize=(8, 8))
plt.scatter(points_class_1[:, 0], points_class_1[:, 1], color='blue', label='Clase 1')
plt.scatter(points_class_2[:, 0], points_class_2[:, 1], color='red', label='Clase 2')

#Formato
plt.title('Puntos no linealmente separables')
plt.xlabel('Eje X')
plt.ylabel('Eje Y')
plt.gca().set_aspect('equal', adjustable='box')
plt.legend()

plt.show()

In [ ]:
#CASO LINEALMENTE SEPARABLE

dataset = separar(0.7, points_class_1a, points_class_2a)
x_train = dataset[0]
y_train = dataset[1]
x_val = dataset[2]
y_val = dataset[3]

pesos = np.random.normal(loc=1, scale=0.2, size=x_train.shape[1])
b = np.random.normal(loc=1, scale=0.2, size=1)
lr = 0.1
#N = x_train.shape[0]
perdida = []
validacion = []

for i in range(1000):
    optimizar(x_train, y_train)
    perdida.append(loss(x_train, y_train))
    validacion.append(loss(x_val, y_val))
    
plt.plot(perdida, color = 'red', label ='Error de entrenamiento')
plt.plot(validacion, color ='blue', label='Error de validación')

plt.title('Optimización del modelo')
plt.xlabel('Epochs')
plt.ylabel('Función de error')

plt.legend()
plt.show()

In [ ]:
#CASO NO LINEALMENTE SEPARABLE

dataset = separar(0.7, points_class_1, points_class_2)
x_train = dataset[0]
y_train = dataset[1]
x_val = dataset[2]
y_val = dataset[3]

pesos = np.random.normal(loc=1, scale=0.2, size=x_train.shape[1])
b = np.random.normal(loc=1, scale=0.2, size=1)
lr = 0.1
#N = x_train.shape[0]
perdida = []
validacion = []

for i in range(1000):
    optimizar(x_train, y_train)
    perdida.append(loss(x_train, y_train))
    validacion.append(loss(x_val, y_val))
    
plt.plot(perdida, color = 'red', label ='Error de entrenamiento')
plt.plot(validacion, color ='blue', label='Error de validación')

plt.title('Optimización del modelo')
plt.xlabel('Epochs')
plt.ylabel('Función de error')

plt.legend()
plt.show()